vault-diff/src/test/java/org/apache/jackrabbit/vault/util/diff/DiffTest.java

JCRVLT-444: DiffTest failure on Windows

---

.travis.yml
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/impl/AdvancedFilterValidator.java
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/impl/AdvancedFilterValidatorFactory.java
vault-validation/src/test/java/org/apache/jackrabbit/vault/validation/spi/impl/AdvancedFilterValidatorTest.java

reuse the same DocumentBuilderFactory for all validators

JCRVLT-446 make test locale agnostic

---

parent/pom.xml
vault-cli/src/main/java/org/apache/jackrabbit/vault/cli/VaultFsApp.java
vault-cli/src/main/java/org/apache/jackrabbit/vault/util/console/AbstractApplication.java
vault-core/pom.xml
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/api/RepositoryFactory.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/api/package-info.java
vault-core/src/main/java/org/apache/jackrabbit/vault/util/RepositoryProvider.java
vault-core/src/main/java/org/apache/jackrabbit/vault/util/package-info.java
vault-davex/src/main/java/org/apache/jackrabbit/vault/davex/DAVExRepositoryFactory.java
vault-doc/src/site/markdown/rcp.md
vault-doc/src/site/markdown/usage.md
vault-rcp/bnd.bnd
vault-rcp/pom.xml
vault-rcp/src/main/java/org/apache/jackrabbit/vault/rcp/RcpTask.java
vault-rcp/src/main/java/org/apache/jackrabbit/vault/rcp/RcpTaskManager.java
vault-rcp/src/main/java/org/apache/jackrabbit/vault/rcp/impl/ConnectionOptionsMixin.java
vault-rcp/src/main/java/org/apache/jackrabbit/vault/rcp/impl/RcpServlet.java
vault-rcp/src/main/java/org/apache/jackrabbit/vault/rcp/impl/RcpTaskImpl.java
vault-rcp/src/main/java/org/apache/jackrabbit/vault/rcp/impl/RcpTaskManagerImpl.java
vault-rcp/src/main/java/org/apache/jackrabbit/vault/rcp/impl/WorkspaceFilterDeserializer.java
vault-rcp/src/test/java/org/apache/jackrabbit/vault/rcp/impl/RcpTaskManagerImplTest.java
vault-sync/pom.xml

Depends upon https://github.com/apache/jackrabbit/pull/92.
obsoletes both #76 and #64.

JCRVLT-419 allow to parameterize connection options

---

vault-cli/src/main/java/org/apache/jackrabbit/vault/cli/CmdExport.java
vault-cli/src/main/java/org/apache/jackrabbit/vault/cli/CmdExportCli.java
vault-cli/src/main/java/org/apache/jackrabbit/vault/cli/CmdImportCli.java
vault-cli/src/main/java/org/apache/jackrabbit/vault/util/console/AbstractApplication.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/SerializerArtifact.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/JcrPackageImpl.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/JcrPackageManagerImpl.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/registry/impl/FSPackageRegistry.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/registry/impl/JcrPackageRegistry.java
vault-sync/src/main/java/org/apache/jackrabbit/vault/sync/impl/SyncLog.java
vault-sync/src/main/java/org/apache/jackrabbit/vault/sync/impl/TreeSync.java
vault-vlt/src/main/java/org/apache/jackrabbit/vault/vlt/VltFile.java
vault-vlt/src/main/java/org/apache/jackrabbit/vault/vlt/meta/xml/zip/UpdateableZipFile.java

JCRVLT-478 fix Sonar issues

---

vault-validation/src/test/java/org/apache/jackrabbit/vault/validation/spi/impl/nodetype/NodeTypeValidatorTest.java
vault-validation/src/test/resources/test-nodetypes.cnd

this is a draft PR to create a unit test that reproduces the problem (which it does not yet).

JCRVLT-485 unit test to reproduce the problem with mix:versionable properties [WIP]

---

vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/JcrPackageDefinition.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/PackageProperties.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/JcrPackageDefinitionImpl.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/JcrPackageDefinitionMetaInf.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/PackagePropertiesImpl.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/package-info.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/impl/JcrPackageDefinitionImplTest.java
vault-core/src/test/resources/test-packages/principalbased.zip/META-INF/vault/properties.xml

rely on PackageProperties API for reading from package
expose unwrapped package properties without type conversions

JCRVLT-499 parse dates with timezone designator "Z" correctly

---

vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/impl/OakIndexDefinitionValidatorFactory.java
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/impl/PackageTypeValidator.java
vault-validation/src/test/java/org/apache/jackrabbit/vault/validation/spi/impl/PackageTypeValidatorTest.java

JCRVLT-513 ignore "allowIndexDefinition" property in package type

---

vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/PackagePropertiesImpl.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/impl/JcrPackageDefinitionImplIT.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/impl/PackagePropertiesImplTest.java

Based on a suggestion by Julian Sedding

JCRVLT-526 improved support of legacy timezone designators "+hhmm"

---

parent/pom.xml
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/DocViewSAXImporter.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/FolderArtifactHandler.java
vault-core/src/main/java/org/apache/jackrabbit/vault/util/EffectiveNodeType.java
vault-core/src/main/java/org/apache/jackrabbit/vault/util/package-info.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/integration/FolderArtifactHandlerIT.java
vault-core/src/test/java/org/apache/jackrabbit/vault/util/EffectiveNodeTypeIT.java
vault-core/src/test/resources/org/apache/jackrabbit/vault/packaging/integration/cqComponent.cnd
vault-core/src/test/resources/org/apache/jackrabbit/vault/util/mynodetypes.cnd
vault-core/src/test/resources/test-packages/intermediate_folders.zip/META-INF/vault/filter.xml
vault-core/src/test/resources/test-packages/intermediate_folders.zip/META-INF/vault/properties.xml
vault-core/src/test/resources/test-packages/intermediate_folders.zip/jcr_root/.content.xml
vault-core/src/test/resources/test-packages/intermediate_folders.zip/jcr_root/testroot/myfolder/mychild/.content.xml

nt:hierarchyNode
Both types have too many restrictions to be useful as intermediate node
types

JCRVLT-544 never create intermediate nodes of type nt:base or

---

vault-core/src/main/java/org/apache/jackrabbit/vault/fs/api/ImportInfo.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/AutoSave.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/Importer.java
vault-core/src/main/java/org/apache/jackrabbit/vault/util/RepositoryCopier.java

exceptions during save()
Reuse AutoSave helper also in RepositoryCopier.

JCRVLT-547 distinguish between recoverable and non-recoverable

---

.travis.yml
parent/pom.xml
src/site/markdown/importmode.md
src/site/markdown/referenceablenodes.md
src/site/site.xml
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/api/IdConflictPolicy.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/api/package-info.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/AbstractArtifactHandler.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/DocViewSAXImporter.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/FileArtifactHandler.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/FolderArtifactHandler.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/GenericArtifactHandler.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/JcrSysViewTransformer.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/NodeStash.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/AutoSave.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/ImportOptions.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/Importer.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/ZipVaultPackage.java
vault-core/src/main/java/org/apache/jackrabbit/vault/util/DocViewNode.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/integration/ImportIT.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/integration/ReferenceableIdentifiersImportIT.java
vault-core/src/test/resources/test-packages/referenceable.zip/META-INF/vault/config.xml
vault-core/src/test/resources/test-packages/referenceable.zip/META-INF/vault/definition/.content.xml
vault-core/src/test/resources/test-packages/referenceable.zip/META-INF/vault/filter.xml
vault-core/src/test/resources/test-packages/referenceable.zip/META-INF/vault/nodetypes.cnd
vault-core/src/test/resources/test-packages/referenceable.zip/META-INF/vault/properties.xml
vault-core/src/test/resources/test-packages/referenceable.zip/jcr_root/.content.xml
vault-core/src/test/resources/test-packages/referenceable.zip/jcr_root/tmp/.content.xml
vault-core/src/test/resources/test-packages/referenceable.zip/jcr_root/tmp/referenceable.xml

add additional import options to tweak UUID collision behavior

JCRVLT-551 try to set UUID from package

---

vault-validation/bnd.bnd
vault-validation/min-target.bndrun
vault-validation/pom.xml

include all non-exported classes/packages from Vault Core
embed jcr2spi

JCRVLT-576 make vault-validation runnable in OSGi container

---

vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/DocViewSAXFormatter.java
vault-core/src/test/java/org/apache/jackrabbit/vault/fs/impl/io/DocViewSaxFormatterIT.java

releng: add integration tests for DocViewSAXFormatter for same-name

---

vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/DocViewSAXFormatter.java
vault-core/src/main/java/org/apache/jackrabbit/vault/util/DocViewNode2.java
vault-core/src/main/java/org/apache/jackrabbit/vault/util/DocViewProperty2Comparator.java
vault-core/src/main/java/org/apache/jackrabbit/vault/util/package-info.java

This allows to write enhanced docview XML without an underlying
repository.

JCRVLT-624 add write methods to DocViewNode2

---

suppressions.xml
target-osgi-environment/pom.xml
vault-core/pom.xml
vault-davex/pom.xml
vault-hook-externalclass-test/pom.xml
vault-rcp/bnd.bnd
vault-rcp/pom.xml
vault-rcp/src/main/java/org/apache/jackrabbit/vault/rcp/impl/RcpServlet.java
vault-rcp/src/main/java/org/apache/jackrabbit/vault/rcp/impl/TypedMapWrapper.java
vault-rcp/src/test/java/org/apache/jackrabbit/vault/rcp/impl/TypedMapWrapperTest.java
vault-sync/pom.xml
vault-validation/pom.xml
vault-vlt/pom.xml

Ignore false-positive warning for
https://www.cve.org/CVERecord?id=CVE-2022-32549

JCRVLT-640 get rid of Sling Commons Classloader and JSON dependencies

---

parent/pom.xml

update dependency-check-maven to 7.1.1

releng: Use ASF Parent 27

---

vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/impl/nodetype/JcrNodeTypeMetaDataImpl.java
vault-validation/src/test/java/org/apache/jackrabbit/vault/validation/spi/impl/nodetype/JcrNodeTypeMetaDataImplTest.java

JcrNodeTypeMetaDataImpl.fulfillsNodeDefinition

JCRVLT-664 prevent potential NPE in

---

parent/pom.xml
vault-core/pom.xml

Upgrade dependency-check-maven 8.1.0

Update to Woodstox 6.5

---

vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/AutoSave.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/ImportOptions.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/Importer.java
vault-core/src/test/java/org/apache/jackrabbit/vault/fs/io/AutoSaveTest.java

Importer.run(...)
Clarify javadoc around persisting the session.

JCRVLT-690 Allow to prevent Session.save() and Session.refresh(false) in

---

vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/impl/util/ValidatorDocViewParserHandler.java
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/NodeContext.java
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/ValidationMessage.java
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/package-info.java
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/util/NodeContextImpl.java
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/util/package-info.java
vault-validation/src/test/java/org/apache/jackrabbit/vault/validation/DocumentViewParserValidatorTest.java

Leverage that when available for creating more detailed ValidationMessages

JCRVLT-704 expose line and columnn from NodeContext

---

Jenkinsfile
parent/pom.xml
vault-cli/pom.xml
vault-core-it/pom.xml
vault-core-it/vault-core-it-execution/vault-core-it-execution-jr2-min/pom.xml

Cleanup and update maven-dependency-plugin/jacoco-maven-plugin to 8.3.1/0.8.10

JCRVLT-710 Update to ASF parent 30

---

parent/pom.xml
pom.xml
target-osgi-environment/max-target-osgi-environment/pom.xml
target-osgi-environment/min-target-osgi-environment/pom.xml
target-osgi-environment/pom.xml
vault-cli/pom.xml
vault-core-it/pom.xml
vault-core-it/vault-core-integration-tests/pom.xml
vault-core-it/vault-core-it-execution/pom.xml
vault-core-it/vault-core-it-execution/vault-core-it-execution-jr2-min/pom.xml
vault-core-it/vault-core-it-execution/vault-core-it-execution-oak-max/pom.xml
vault-core-it/vault-core-it-execution/vault-core-it-execution-oak-min/pom.xml
vault-core-it/vault-core-it-support/pom.xml
vault-core-it/vault-core-it-support/vault-core-it-support-api/pom.xml
vault-core-it/vault-core-it-support/vault-core-it-support-jackrabbit/pom.xml
vault-core-it/vault-core-it-support/vault-core-it-support-oak/pom.xml
vault-core/pom.xml
vault-davex/pom.xml
vault-diff/pom.xml
vault-hook-example/pom.xml
vault-hook-externalclass-test/pom.xml
vault-rcp/pom.xml
vault-sync/pom.xml
vault-validation/pom.xml
vault-vlt/pom.xml

mechanical part done with:
~~~
for i in $(find . -name pom.xml); do sed -i 's/3.7.3-SNAPSHOT/${revision}/g' $i; done
~~~

JCRVLT-726: Release Jackrabbit Filevault 3.7.2 - cleanup version information past release

---

Jenkinsfile
parent/pom.xml

Leverage API key from Jenkins secret

Update to dependency-check 10.0.3

---

src/site/markdown/filter.md
src/site/markdown/importmode.md
src/site/markdown/properties.md
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/config/DefaultWorkspaceFilter.java

Clarify documentation of import modes to explicitly only outline lowercase values.

JCRVLT-788 improve exception message for invalid import modes

---

parent/pom.xml

Update to dependency-check 12.1

---

parent/pom.xml
target-osgi-environment/min-target-osgi-environment/min-target.bndrun
vault-core-it/vault-core-integration-tests/pom.xml
vault-core-it/vault-core-integration-tests/src/main/java/org/apache/jackrabbit/vault/packaging/impl/JcrPackageManagerImplIT.java
vault-core-it/vault-core-integration-tests/src/main/java/org/apache/jackrabbit/vault/packaging/integration/ACEsAtRootIT.java
vault-core/pom.xml
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/config/ConfigHelper.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/config/Registry.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/InstallHookProcessorImpl.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/registry/impl/ExecutionPlanBuilderImplTest.java
vault-rcp/pom.xml

[JCRVLT-764] Require Java 11
