vault-core/src/test/java/org/apache/jackrabbit/vault/fs/impl/io/CompressionUtilTest.java

As compressibility is just a best effort guess, just running the test
once you change the algorithm is enough

JCRVLT-441 don't execute tests which are not 100% reliable

---

vault-validation/src/main/resources/filter.xsd

I noticed that the filter `mode` attribute is simply defined as a string, rather than a reference to the `mode` attribute definition from line 33.
It may result in incorrect schema validations, because any string will be allowed, instead of: `replace`, `merge`, `update`.

Fix filter mode attribute definition in filter.xsd

---

vault-core/src/main/java/org/apache/jackrabbit/vault/util/PlatformNameFormat.java
vault-core/src/test/java/org/apache/jackrabbit/vault/util/PlatformNameTest.java

Minor cleanups + a failing test case.

JCRVLT-488 - PlatformNameFormat incorrectly sets repository names for nodes with double colons

---

vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/impl/nodetype/JcrNodeTypeMetaDataImpl.java
vault-validation/src/test/java/org/apache/jackrabbit/vault/validation/spi/impl/nodetype/NodeTypeValidatorTest.java

JCRVLT-497 correctly switch context if authorizable node is first

---

vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/JarExporter.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/PackageManagerImpl.java

JcrPackageManager.rewrap(...) and assemble(...)

JCRVLT-448 always close output stream passed to

---

vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/ImportOptions.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/Importer.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/package-info.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/JcrPackageImpl.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/JcrPackageManagerImpl.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/PackagingImpl.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/ZipVaultPackage.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/registry/impl/AbstractPackageRegistry.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/registry/impl/FSPackageRegistry.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/registry/impl/JcrPackageRegistry.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/integration/PackageInstallIT.java

the strict default value can be modified via OSGi configuration and can
still be overwritten with ImportOptions.setStrict(boolean)

JCRVLT-509 make importer strict by default

---

vault-core/src/main/java/org/apache/jackrabbit/vault/util/DocViewProperty.java
vault-core/src/main/java/org/apache/jackrabbit/vault/util/package-info.java
vault-core/src/test/java/org/apache/jackrabbit/vault/util/DocViewPropertyTest.java

provide factory methods taking either Property or Value[]
allow to format a given DocViewProperty

JCRVLT-516 simplify usage of DocViewProperties outside JCR context

---

vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/registry/impl/FSInstallState.java

When the FSPackageRegistry is updated such that the XML files that save the state for each package will become corrupt if they are shorter than before. They are not truncated when they are rewritten, and if they become shorter, there are remnants of the old XML after the end of the newly written XML, so that there is a SAXParseException when they are read again). This is a simple fix that solves that problem and makes it usable again.

JCRVLT-525 fix corruption of the XML files of the FSPackageRegistry

---

vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/FolderArtifactHandler.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/integration/FolderArtifactHandlerIT.java
vault-core/src/test/resources/test-packages/test_nodetype_on_merge.zip/META-INF/vault/config.xml
vault-core/src/test/resources/test-packages/test_nodetype_on_merge.zip/META-INF/vault/definition/.content.xml
vault-core/src/test/resources/test-packages/test_nodetype_on_merge.zip/META-INF/vault/filter.xml
vault-core/src/test/resources/test-packages/test_nodetype_on_merge.zip/META-INF/vault/nodetypes.cnd
vault-core/src/test/resources/test-packages/test_nodetype_on_merge.zip/META-INF/vault/properties.xml
vault-core/src/test/resources/test-packages/test_nodetype_on_merge.zip/jcr_root/.content.xml
vault-core/src/test/resources/test-packages/test_nodetype_on_merge.zip/jcr_root/home/groups/.content.xml
vault-core/src/test/resources/test-packages/test_nodetype_on_merge.zip/jcr_root/home/groups/test/.content.xml
vault-core/src/test/resources/test-packages/test_nodetype_on_merge.zip/jcr_root/home/groups/test/lXZzTxX_ZZkvjixvqJON/.content.xml

Correctly register modification of primary type for mode REPLACE
Co-authored-by: Dominik Suess <suess@adobe.com>

JCRVLT-542 do not modify primary types for import mode != REPLACE

---

vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/DocViewSAXImporter.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/integration/EmptyPackageIT.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/integration/ImportIT.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/integration/IntegrationTestBase.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/integration/PackageInstallIT.java
vault-core/src/test/resources/test-packages/property_constraint_violation.zip/META-INF/vault/filter.xml
vault-core/src/test/resources/test-packages/property_constraint_violation.zip/META-INF/vault/nodetypes.cnd
vault-core/src/test/resources/test-packages/property_constraint_violation.zip/META-INF/vault/properties.xml
vault-core/src/test/resources/test-packages/property_constraint_violation.zip/jcr_root/.content.xml
vault-core/src/test/resources/test-packages/property_constraint_violation.zip/jcr_root/testroot/.content.xml
vault-core/src/test/resources/test-packages/protected_properties.zip/META-INF/vault/filter.xml
vault-core/src/test/resources/test-packages/protected_properties.zip/META-INF/vault/nodetypes.cnd
vault-core/src/test/resources/test-packages/protected_properties.zip/META-INF/vault/properties.xml
vault-core/src/test/resources/test-packages/protected_properties.zip/jcr_root/.content.xml
vault-core/src/test/resources/test-packages/protected_properties.zip/jcr_root/testroot/.content.xml

dynamically determine if a property is protected
fail with an exception for all other constraint violations (in mode =
REPLACE)

JCRVLT-543 ignore protected properties during import

---

vault-core/pom.xml
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/package-info.java

classes could have never been referenced from other bundles in an OSGi
environment (due to private super class)

JCRVLT-546 only increase minor version of o.a.j.v.fs as the removed

---

vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/VaultPackage.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/PackagePropertiesImpl.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/ZipVaultPackage.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/impl/ZipVaultPackageIT.java

never log and throw, but only one or the other!

JCRVLT-561 prevent stack overflow in getArchive() for closed packages

---

vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/ValidationExecutor.java
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/impl/DocumentViewParserValidatorFactory.java
vault-validation/src/test/java/org/apache/jackrabbit/vault/validation/ValidationExecutorTest.java

ValidationExecutor.validateGenericJcrData
This happened in case validator "jackrabbit-docviewparser" was disabled
and there were no nodePaths being collected

JCRVLT-578 Prevent NoSuchElementException in

---

vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/registry/impl/FSInstallStateCache.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/registry/impl/FSPackageRegistryTest.java

Functional changes besides logging:
1. do not call "createDirectories" when the path already exists (this avoids a failure when the last path segment is a symlink)
2. when walking the homeDir, follow symlinks

JCRVLT-575: handle symlinks in homeDir path

---

vault-core/pom.xml
vault-validation/pom.xml

JCRVLT-593 mark embedded dependencies as scope "provided" as they should

---

vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/AutoSave.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/Importer.java
vault-core/src/test/java/org/apache/jackrabbit/vault/fs/io/AutoSaveTest.java

Verify that counters behave correctly

JCRVLT-647 restore old save() interval after failed save() attempts

---

vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/Importer.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/JcrPackageImpl.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/impl/ZipVaultPackage.java
vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/registry/impl/FSPackageRegistry.java

fix incorrect overwrite of explicit policy
apply default also for FSPackages

JCRVLT-650: apply default id conflict policy as late as possible

---

vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/registry/impl/JcrPackageRegistry.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/integration/PackageRegistryIT.java

JCRVLT-662: JcrPackageRegistry.remove() leaks temp file

---

parent/pom.xml
suppressions.xml
vault-core/pom.xml

Update embedded Woodstox however to newest 6.4.0
Update dependency-check to newest 7.4.1

JCRVLT-674 ignore dependency-check false positives

---

vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/impl/nodetype/JcrNodeTypeMetaDataImpl.java
vault-validation/src/test/java/org/apache/jackrabbit/vault/validation/spi/impl/nodetype/JcrNodeTypeMetaDataImplTest.java
vault-validation/src/test/java/org/apache/jackrabbit/vault/validation/spi/impl/nodetype/NodeTypeValidatorTest.java

finalizeValidationForSiblings/Subtree

JCRVLT-703 always use original node context when reporting violations in

---

vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/DocViewSAXFormatter.java
vault-core/src/test/java/org/apache/jackrabbit/vault/fs/impl/io/DocViewSaxFormatterIT.java

Properties with special names should only be excluded from the export in case they are really protected.
In some cases "jcr:created" properties are unprotected.

JCRVLT-705 export special properties which are not protected

---

vault-core/src/main/java/org/apache/jackrabbit/vault/fs/impl/io/DocViewSAXHandler.java
vault-validation/src/test/java/org/apache/jackrabbit/vault/validation/DocumentViewParserValidatorTest.java

Must point to currently ended node not to its parent

JCRVLT-718 fix DocViewParserHandler.endDocViewNode's nodePath argument

---

vault-core-it/vault-core-integration-tests/src/main/java/org/apache/jackrabbit/vault/fs/spi/impl/jcr20/JackrabbitACLManagementIT.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/spi/impl/jcr20/JackrabbitACLManagement.java

Replaces the user/group creation test for determining the usersPath and groupsPath config values with a condition based only on the nodetype for the node being removed.

JCRVLT-721 check for rep:AuthorizableFolder nodetype before principal policy search

---

vault-core-it/vault-core-integration-tests/src/main/java/org/apache/jackrabbit/vault/sync/impl/VaultSyncServiceImplIT.java
vault-core/src/main/java/org/apache/jackrabbit/vault/fs/io/PlatformExporter.java

Improve the platform exporter:
- Pruning
keep track of the used directories and delete unused directories when pruning
- Tracking
Track file creation with the correct action ('A', 'U').
Track directory creation only - no tracking for existing directories
after #316

Improve the platform exporter

---

vault-rcp/src/main/java/org/apache/jackrabbit/vault/rcp/impl/RcpTaskImpl.java

After a lot of searching I found the following error in the class "org.apache.jackrabbit.vault.rcp.impl.RcpTaskImpl":
private static WorkspaceFilter createFilterForExcludes(List<String> excludes) throws ConfigurationException {
// could be done better
DefaultWorkspaceFilter srcFilter = new DefaultWorkspaceFilter();
PathFilterSet filterSet = new PathFilterSet("/");
for (String path : excludes) {
filterSet.addExclude(new DefaultPathFilter(path));
}
**srcFilter.add(filterSet);**
return srcFilter;
}
The line marked bold was missing.

add missing filterSet to scrFilter

---

parent/pom.xml
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/impl/util/ValidatorDocViewParserHandler.java
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/NodeContext.java
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/package-info.java
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/util/NodeContextImpl.java
vault-validation/src/main/java/org/apache/jackrabbit/vault/validation/spi/util/package-info.java

This allows validator implementations to emit more user-friendly node/property names (leveraging qualified instead of expanded name).

JCRVLT-761 add method to generate qualified name from SPI name object

---

parent/pom.xml

This is to also include directories/files containing "target" in their name in the source-release archive

JCRVLT-760 Use apache-source-release-assembly-descriptor 1.7

---

vault-core/src/main/java/org/apache/jackrabbit/vault/packaging/VersionRange.java
vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/VersionRangeTest.java

fromString(String)
This reduces memory footprint

JCRVLT-778 Always return singleton INFINITE for empty string in

---

parent/pom.xml
pom.xml
vault-coverage-aggregate/pom.xml

This regressed with
https://github.com/apache/jackrabbit-filevault/commit/43ac160511b7c0ec5938413057924863b5e40191 Aggregate reports should be orthogonal to regular in-module UTs/ITs though.

Restore broken Jacoco configuration

---

parent/pom.xml

This is used downstream and no longer deployed automatically since ASF parent 32 (https://issues.apache.org/jira/browse/MPOM-480)

JCRVLT-783 Deploy site.xml with parent

---

vault-cli/src/main/java/org/apache/jackrabbit/vault/cli/CmdExport.java
vault-cli/src/main/java/org/apache/jackrabbit/vault/cli/CmdExportCli.java

The export does not have meta data, therefore explicitly skip exporting it.

JCRVLT-792 Fix NPE during export CLI command

---

vault-core/src/test/java/org/apache/jackrabbit/vault/packaging/registry/impl/FSPackageRegistryTest.java

JCRVLT-788: use of 'toUppercase' with default locale should be avoided

---

parent/pom.xml
target-osgi-environment/max-target-osgi-environment/pom.xml
target-osgi-environment/min-target-osgi-environment/pom.xml
vault-validation/pom.xml

Test against newest Oak 1.82.0 and JR2 2.22.1
Minimum OSGi runtime dependencies remain unchanged

JCRVLT-790 Really upgrade embedded JR2 dependencies to 2.22.1

---

parent/pom.xml
vault-cli/pom.xml
vault-rcp/pom.xml
vault-sync/pom.xml
vault-validation/pom.xml

higher
This is severity MEDIUM or above
(https://nvd.nist.gov/vuln-metrics/cvss)

Fail build when dependency-check finds dependencies with CVSS 4 or
